
modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/Rustic/issues"
[[mods]]
modId = "rustic"
version = "${version}"
displayName = "Rustic"
displayURL = "https://github.com/terrarium-earth/Rustic"
logoFile = "icon.png"
authors = "Alex Nijjar, CodexAdrian, Facu, Kekie6, ThatGravyBoat"
description = '''
Rustic mod for the Rustic thingy in Minecraft 1.19.2
'''

[[dependencies.rustic]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rustic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rustic]]
modId = "botarium"
mandatory = true
versionRange = "[1.8.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rustic]]
modId = "resourcefullib"
mandatory = true
versionRange = "[1.1.18,)"
ordering = "NONE"
side = "BOTH"